### ISSUE TITLE
Graphical misbehavior

### ISSUE THREAD

**Issue by federicoiosue** [Shusshu/Android-RecurrencePicker#14]
Hi @Shusshu, thanks for your library!

Any idea about why recurrent picker is shown like this?

![selezione_025](https://cloud.githubusercontent.com/assets/487104/6807869/6cfd3114-d251-11e4-958e-d9f7e380437a.png)

I successfully included into my application using it with iCal4j but I'm still facing this graphical issue.

Any hint? Thanks

**Comment by Shusshu** [comment]
I would need more info to reproduce that...

Do you have a sample project?

**Comment by federicoiosue** [comment]
Ok, I built a sample project from scratch and it worked.

Sto I started stripping out styles (being a graphical issue I started from there) and I found that I was overriding

**Comment by federicoiosue** [comment]
Ok, I built a sample project from scratch and it worked.

Sto I started stripping out styles (being a graphical issue I started from there) and I found that I was overriding default buttons as a workaround with another library issue.

```
<item name="android:button">@android:drawable/checkbox_off_background</item>
```

So, obviously, the problem was not related to *Android-RecurrencePicker* library itself.

Thanks!

**Comment by Shusshu** [comment]
Great!
